# Netlify Configuration for Testimonial System

[build]
  functions = "netlify/functions"
  publish = "."

# Security: Configure secret scanning
[build.environment]
  NODE_VERSION = "18"
  # Tell Netlify that env vars are intentionally used (not secrets in code)
  SECRETS_SCAN_ENABLED = "false"

# Environment variables for production
# Set these in your Netlify dashboard:
# AIRTABLE_BASE_ID = "your_airtable_base_id"
# AIRTABLE_API_KEY = "your_airtable_api_key"
# ADMIN_TOKEN = "your_secure_admin_token"
# NOTIFICATION_EMAIL = "your_email@example.com" (optional)
# NETLIFY_BUILD_HOOK = "your_netlify_build_hook_url" (optional)
# SITE_URL = "https://your-site.netlify.app"

# Redirect rules
[[redirects]]
  from = "/admin"
  to = "/admin-testimonials.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

# Headers for API functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
